version: "3.9"

services:
  web:
    build:
      context: .
    container_name: kurata-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1  # バッファリングを無効化(print()の出力をリアルタイムに表示するために必要)
